name: DefaultCI

on:
  push:
    branches:
      - master
  # Update the image every now and then
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 14 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  default-build:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: checkout
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y jq wget
      - name: set script permissions
        run: chmod +x ./scripts/ci-push.sh ./scripts/image-build.sh ./scripts/image-push.sh  ./scripts/getVersion.sh
      - name: login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build dev
        run: ./scripts/ci-push.sh $IMAGE dev $(./scripts/getVersion.sh dev)
      - name: build rc
        run: ./scripts/ci-push.sh $IMAGE rc $(./scripts/getVersion.sh rc)
      - name: build release
        run: ./scripts/ci-push.sh $IMAGE release $(./scripts/getVersion.sh release)
      - name: logout from DockerHub
        run: docker logout
